project_id = "iagnculfrgjpkjlihvem"

[functions.generate-resume]
verify_jwt = false

[functions.wallet-auth]
verify_jwt = false

[functions.ipfs-upload]
verify_jwt = false

[functions.register-issuer]
verify_jwt = false